name: "godot-ci export linux"
on: push

env:
  GODOT_VERSION: 4.0.1
  EXPORT_NAME: game-off

jobs:
  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.2.1
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
